# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6a15bc01593daff5541065ba84e36a4428878ea37387b717916246624ec072c86f519572301385532502439005c5a306f279929a6642a5104d0c6b08b85c5d

test:
  secret_key_base: 24fc81fe724cc24f76645e17e7fbab82146683f3296ba41abb6a7ce7821734661f998f9ae3f54a5b4b3df322448097bc5614c128e7c26b0a096f8022bfce1ff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
